module.exports = {
  container: {
    height: "75px",
    boxShadow: "0 1px 10px rgba(0, 0, 0, 0.1)",
  },
  component: {
    padding: "0px",
    float: "none",
    margin: "0px auto",
  },
  logo: {
    height: "75px",
    padding: "26px 0px",
    cursor: "pointer",
  },
  nav: {
    display: "inline-block",
    float: "right",
    listStyle: "none",
    height: "75px",
    margin: "0px",
  },
  navButton: {
    fontSize: "22px",
    height: "75px",
    lineHeight: "75px",
    padding: "0 25px",
    cursor: "pointer",
    textTransform: "uppercase",
    color: "#777",
    backgroundColor: "white",
    display: "inline-block",
  },
  navButtonHovered: {
    fontSize: "22px",
    height: "75px",
    lineHeight: "75px",
    padding: "0 25px",
    cursor: "pointer",
    textTransform: "uppercase",
    color: "white",
    backgroundColor: "#4FAFC2",
    display: "inline-block",
  },
}
