module.exports = {
  textarea: {
    width: "100%",
    maxWidth: "100%",
    minHeight: "115px",
    maxHeight: "350px",
    padding: "0 6px 0 8px",
    cursor: "pointer",
    border: "1px solid #777",
    backgroundColor: "#eee",
  },
  textareaFocused: {
    width: "100%",
    maxWidth: "100%",
    minHeight: "115px",
    maxHeight: "350px",
    padding: "0 6px 0 8px",
    border: "1px solid #4fafc2",
    cursor: "auto",
    backgroundColor: "#ffffff",
  },
  textareaHovered: {
    width: "100%",
    maxWidth: "100%",
    minHeight: "115px",
    maxHeight: "350px",
    padding: "0 6px 0 8px",
    border: "1px solid #777",
    cursor: "pointer",
    backgroundColor: "#ffffff",
  },
  textareaHoveredFocused: {
    width: "100%",
    maxWidth: "100%",
    minHeight: "115px",
    maxHeight: "350px",
    padding: "0 6px 0 8px",
    border: "1px solid #4fafc2",
    cursor: "auto",
    backgroundColor: "#ffffff",
  },
}
